name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: raissa.brizeno@gmail.com
        password: dckr_pat_twBu8tCgMEnap1eJZp7Ul4_WrI0

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./exercicios/para-sala/users-api-aula
        push: true
        tags: raissabrizeno/users-api-aula:1.0.0

    - name: Log out from Docker Hub
      run: docker logout
