name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout 
      uses: actions/checkout@v4
      with:
        path: ecercicios/para-sala/users-api-aula

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: raissabrizeno
        password: dckr_pat_FA_dtQWNNB6w7ki2NTKNTwB76U4
    
    - name: Build and push
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        context: ./
        push: true
        tags: raissabrizeno/users-api-aula:1.0.0
