name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4


    - uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      run: echo dckr_pat_FA_dtQWNNB6w7ki2NTKNTwB76U4 | docker login -u raissabrizeno --password-stdin


    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./exercicios/para-sala/users-api-aula
        push: true
        tags: raissabrizeno/users-api-aula:1.0.0

    - name: Log out from Docker Hub
      run: docker logout
